---
title: "SICVIR: resumen de variables"
format:
  html: 
     self-contained: true
     fig-width: 8
     fig-height: 3
     fig-align: "center"
     toc: true
     toc-title: "Contenidos"
     toc-location: left
     toc-expand: 1
     toc-depth: 3
     number-sections: false
execute: 
  echo: false
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---


```{r setup}
library(dplyr)
library(readr)
library(purrr)
library(gt)
library(pander)
library(here)
library(tidyr)
library(glue)
library(ggplot2)
library(scales)
library(patchwork)
```

```{r datos}
# sicvir <- read_csv2(here("datos/sicvir_indicadores_rurales.csv"))
# etiquetas <- read_csv2(here("datos/sicvir_etiquetas.csv"))
sicvir <- read_csv2(here("datos/sicvir_indicadores_rurales_2025.csv"))
etiquetas <- read_csv2(here("datos/sicvir_etiquetas_2025.csv"))

# variables <- etiquetas |> 
#   slice(9:n()) |> 
#   pull(campo)
variables <- etiquetas |>
  filter(!is.na(ultima_medicion)) |> 
  pull(campo)
```


```{r}
# walk(etiquetas$campo, ~{
#   sicvir |> 
#     select(all_of(.x)) |> 
#     gt()
# })
```

```{r results = "asis"}
walk(variables, \(variable) {
  # variable <- variables[2]
  
  titulo <- etiquetas |> 
    filter(campo == variable) |> 
    pull(descripcion)
  
  pandoc.header(titulo, level = 3)
  pandoc.p(paste("Variable", pandoc.emphasis.return(variable)))
  
  datos_variable <- sicvir |>
    select(comuna, region, !!sym(variable))
  
  datos_variable_validos <- datos_variable |> 
    filter(!is.na(!!sym(variable)))
    
  n_no_perdidos <- nrow(datos_variable_validos)
  porcentaje <- percent(n_no_perdidos/nrow(sicvir), accuracy = 0.01)
  
  pandoc.p(glue("Comunas con datos en la variable: {n_no_perdidos} ({porcentaje})"))
  
  # estadísticos descriptivos
  percentiles <- datos_variable_validos |> 
    summarize(promedio = mean(!!sym(variable)),
              min = min(!!sym(variable)),
              p_25 = quantile(!!sym(variable), .25),
              p_50 = median(!!sym(variable)),
              p_60 = quantile(!!sym(variable), .60),
              p_75 = quantile(!!sym(variable), .75),
              max = max(!!sym(variable)))
  
  # tabla
  tabla_percentiles <- percentiles |>   
    gt() |>
    data_color(rows = 1, palette = "Blues", direction = "row", 
               domain = c(percentiles$p_25, percentiles$max),
               na_color = "white") |> 
    fmt_number(decimals = 1, dec_mark = ",", sep_mark = ".") |> 
    opt_table_lines("none") |> 
    cols_width(everything() ~ px(90)) |> 
    cols_label(
      min = "mínimo",
      p_25 = "25%",
      p_50 = "50%",
      p_60 = "60%",
      p_75 = "75%",
      max = "máximo") |> 
    print(type = "html")
  
  # tabla vertical
  datos_variable_validos |> 
    summarize(p_25 = sum(!!sym(variable) < percentiles$p_25),
              p_50 = sum(!!sym(variable) < percentiles$p_50),
              p_60 = sum(!!sym(variable) < percentiles$p_60),
              p_75 = sum(!!sym(variable) < percentiles$p_75),
              sobre_75 = sum(!!sym(variable) > percentiles$p_75)) |> 
    pivot_longer(cols = everything()) |> 
    mutate(name = case_match(name,
                             "p_25" ~ "bajo 25%",
                             "p_50" ~ "bajo 50%",
                             "p_60" ~ "bajo 60%",
                             "p_75" ~ "bajo 75%",
                             "sobre_75" ~ "sobre 75%")) |> 
    gt() |> 
    cols_align(columns = name, "right") |> 
    cols_align(columns = value, "left") |> 
    cols_label(name = "", value = "Comunas") |> 
    tab_style(locations = cells_column_labels(),
              style = cell_text(weight = "bold")) |> 
    data_color(columns = value, palette = "Blues") |> 
    opt_table_lines("none") |> 
    print(type = "html")
  
  # gráfico
  histograma <- datos_variable |>
    ggplot(aes(!!sym(variable))) +
    geom_histogram(fill = "#317DBB") +
    theme_minimal() +
    theme(axis.title = element_blank()) +
    scale_y_continuous(expand = expansion(c(0, 0.05)))
  
  # poner valor arriba del gráfico
  histograma <- histograma +
    geom_vline(xintercept = percentiles$p_75, 
               linewidth = 1, color = "#09306B") +  
    annotate("text", x = percentiles$p_75, label = " 75%", 
             y = max(layer_data(histograma)$y)*1.01,
             hjust = 0, vjust = 0, size = 4) +
    geom_vline(xintercept = percentiles$p_50, 
               linewidth = 1, color = "#09306B", linetype = "dashed") +  
    annotate("text", x = percentiles$p_50, label = "50% ", 
             y = max(layer_data(histograma)$y)*1.01,
             hjust = 1, vjust = 0, size = 4) 
  
  boxplot <- datos_variable |> 
    ggplot(aes(y = !!sym(variable))) +
    geom_boxplot(fill = "#317DBB", alpha = .4, colour = "#09306B") +
    theme_minimal() +
    theme(axis.title = element_blank())
  
  # unir gráficos
  graficos <- histograma + boxplot +
    plot_layout(widths = c(2, 1))
  
  plot(graficos)
  
  pandoc.p('')
  pandoc.horizontal.rule()
  pandoc.p('')
})

```
